<h1>Strings In Python </h1>

In [5]:
# Creating Strings:
single_quoted = 'Hello, world!'
double_quoted = "Hello, world!"
triple_quoted = '''Hello, world!'''
print(single_quoted)
print(double_quoted)
print(triple_quoted)

# Accessing Characters in Strings:
s = "Hello"
print(s[0])

# String Slicing:
s = "Hello, world!"
print(s[0:5]) 

# String Concatenation:
s1 = "Hello"
s2 = "world"
s3 = s1 + " " + s2
print(s3)  

# Strings Method

print(len(s1))
print(s1.lower())
print(s1.upper())



Hello, world!
Hello, world!
Hello, world!
H
Hello
Hello world
5
hello
HELLO


<h1>Data Types</h1>

In [9]:
# Numeric Types:
integer = 42
Float = 3.14
complex_num = 2 + 3j
print(integer)
print(Float)
print(complex_num)

#Sequence Types:
List = [1, 2, 3, 4, 5]
Tuple = (1, 2, 3, 4, 5)
Range = range(0, 10)
print(List)
print(Tuple)
print(list(Range))

# text type
String = "hello world"
print(String)

#mapping type
dictionary = {'name': 'Alice', 'age': 30}
print(dictionary)

#Set Type:
Set = {1, 2, 3, 4, 5}
print(Set)

#Boolean type
Booleant = True
Booleanf = False
print(Booleant)
print(Booleanf)


42
3.14
(2+3j)
[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
hello world
{'name': 'Alice', 'age': 30}
{1, 2, 3, 4, 5}
True
False


<h1>Loops</h1>

In [10]:
#ForLoop

my_list = [1, 2, 3, 4, 5]
for item in my_list:
    print(item)

my_string = "Hello"
for char in my_string:
    print(char)

for i in range(5):
    print(i)

#While Loop

num = 0
while num < 5:
    print(num)
    num += 1

num = 0
while True:
    print(num)
    num += 1
    if num >= 5:
        break



# Nested loops
for i in range(3):
    for j in range(2):
        print(i, j)


1
2
3
4
5
H
e
l
l
o
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0 0
0 1
1 0
1 1
2 0
2 1


<h1>Conditional Statement</h1>

In [11]:
#If Statement:
x = 5
if x > 0:
    print("x is positive")

# If-else Statement:
x = 5
if x % 2 == 0:
    print("x is even")
else:
    print("x is odd")

# If-elif-else Statement:
x = 5
if x > 0:
    print("x is positive")
elif x < 0:
    print("x is negative")
else:
    print("x is zero")

# Nested If Statement:
x = 5
if x > 0:
    if x % 2 == 0:
        print("x is positive and even")
    else:
        print("x is positive and odd")
else:
    print("x is not positive")


x is positive
x is odd
x is positive
x is positive and odd


<h1>Functions</h1>

In [12]:
# Function without Parameters:
def greet():
    print("Hello, world!")

greet()  

# Function with Parameters:
def greet(name):
    print("Hello,", name)

greet("Alice")

# Function with Default Parameters:
def greet(name="world"):
    print("Hello,", name)

greet()  
greet("Alice") 

#Function with Return Value:
def add(a, b):
    return a + b

result = add(3, 5)
print(result) 

#Recursive Function:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(5))


Hello, world!
Hello, Alice
Hello, world
Hello, Alice
8
120


<h1>Classes</h1>

In [13]:
# Simple Class:
class MyClass:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print("Hello,", self.name)

obj = MyClass("Alice")
obj.greet() 

# Class with Class Variable and Instance Variable:
class Dog:
    species = "Canis"

    def __init__(self, name):
        self.name = name

dog1 = Dog("Buddy")
dog2 = Dog("Molly")

print(dog1.name)  
print(dog2.name) 
print(dog1.species) 
print(dog2.species) 

# Class with Private Members:
class MyClass:
    def __init__(self):
        self.__private_var = 42

    def get_private_var(self):
        return self.__private_var

obj = MyClass()
print(obj.get_private_var())



Hello, Alice
Buddy
Molly
Canis
Canis
42


<h1>Libraries Numpy & Pandas</h1>

**What’s the difference between a Python list and a NumPy array?**

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

**Why use NumPy?**

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [27]:
import numpy as np
arr1 = np.array([3, 5, 1, 4, 2])
print(arr1)

# Functions in NUmpy
arr = np.zeros(2)
print(arr)
arr = np.ones(2)
print(arr)
empty_arr = np.empty(2)
empty_arr[0] = 3.14
empty_arr[1] = 42.0
print(empty_arr)
print(np.sort(arr1))
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))


[3 5 1 4 2]
[0. 0.]
[1. 1.]
[ 3.14 42.  ]
[1 2 3 4 5]
[1 2 3 4 5 6 7 8]


**What kind of data does pandas handle?**

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data. In pandas, a data table is called a DataFrame.

**How do I read and write tabular data?**

pandas supports the integration with many file formats or data sources out of the box (csv, excel, sql, json, parquet,…). Importing data from each of these data sources is provided by function with the prefix read_*. Similarly, the to_* methods are used to store data.

**Why Use Pandas?**

Pandas is used for data manipulation and analysis, offering powerful data structures and tools for working with structured data.

**1.DataFrame:** Pandas provides a DataFrame object, which is a 2-dimensional labeled data structure with columns of potentially different types. It's similar to a spreadsheet or SQL table, making it easy to handle tabular data.

**2.Data Cleaning:** Pandas offers functions and methods for data cleaning tasks such as handling missing data, removing duplicates, and transforming data into the desired format.

**3.Data Manipulation:** It allows for easy manipulation of data, including filtering, selecting, grouping, aggregating, merging, and reshaping data.

**4.Data Analysis:** Pandas provides statistical functions for data analysis, including descriptive statistics, correlation analysis, and time-series analysis.

**5.Integration with Other Libraries:** Pandas integrates well with other Python libraries such as NumPy, Matplotlib, and scikit-learn, providing a powerful ecosystem for data analysis and machine learning.

Overall, Pandas simplifies the process of working with structured data in Python and is widely used in data science, machine learning, and data analysis projects.

In [35]:
import pandas as pd
# Creating a DataFrame:
data = {'Name': ['Babar Azam', 'Shahdab', 'Shaheen Shah'],
        'Age': [30, 30, 25],
        "city": ['lahore','lahore','peshawar']}
df = pd.DataFrame(data)
print(df)
df.to_csv("CricketersInfo.csv")

           Name  Age      city
0    Babar Azam   30    lahore
1       Shahdab   30    lahore
2  Shaheen Shah   25  peshawar


<h1>MANAGING CYBER SECURITY SALARIES DATASET USING PANDAS</h1>

In [37]:
# Reading Data from CSV File:
df = pd.read_csv('salaries_cyber.csv')
print(df.head())

   work_year experience_level employment_type               job_title  salary  \
0       2022               EN              FT   Cyber Program Manager   63000   
1       2022               MI              FT        Security Analyst   95000   
2       2022               MI              FT        Security Analyst   70000   
3       2022               MI              FT     IT Security Analyst  250000   
4       2022               EN              CT  Cyber Security Analyst  120000   

  salary_currency  salary_in_usd employee_residence  remote_ratio  \
0             USD          63000                 US            50   
1             USD          95000                 US             0   
2             USD          70000                 US             0   
3             BRL          48853                 BR            50   
4             USD         120000                 BW           100   

  company_location company_size  
0               US            S  
1               US            

In [38]:
print(df.tail())


      work_year experience_level employment_type  \
1242       2020               MI              FT   
1243       2021               SE              FT   
1244       2021               SE              FT   
1245       2021               MI              FT   
1246       2021               MI              FT   

                         job_title  salary salary_currency  salary_in_usd  \
1242        Cyber Security Analyst  140000             AUD          96422   
1243  Information Security Manager   60000             GBP          82528   
1244  Penetration Testing Engineer  126000             USD         126000   
1245  Information Security Analyst   42000             GBP          57769   
1246   Threat Intelligence Analyst   66310             USD          66310   

     employee_residence  remote_ratio company_location company_size  
1242                 AU            50               AU            M  
1243                 GB            50               GB            L  
1244          

In [39]:
# Basic DataFrame Operations:
print(df.shape)
print(df.columns)
print(df.describe())
print(df['job_title'])

(1247, 11)
Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')
         work_year        salary  salary_in_usd  remote_ratio
count  1247.000000  1.247000e+03    1247.000000   1247.000000
mean   2021.316760  5.608525e+05  120278.218925     71.491580
std       0.715501  1.415944e+07   70291.394942     39.346851
min    2020.000000  1.740000e+03    2000.000000      0.000000
25%    2021.000000  7.975450e+04   74594.500000     50.000000
50%    2021.000000  1.200000e+05  110000.000000    100.000000
75%    2022.000000  1.600800e+05  150000.000000    100.000000
max    2022.000000  5.000000e+08  910991.000000    100.000000
0              Cyber Program Manager
1                   Security Analyst
2                   Security Analyst
3                IT Security Analyst
4             Cyber Security Analyst
                 

<h1>Global Cybersecurity: Geospacial EDA and Insights</h1>

In [40]:
# Reading Data from CSV File:
df1 = pd.read_csv('Cyber_security.csv')
print(df1.head())

       Country        Region    CEI    GCI   NCSI    DDL
0  Afghanistan  Asia-Pasific  1.000   5.20  11.69  19.50
1      Albania        Europe  0.566  64.32  62.34  48.74
2      Algeria        Africa  0.721  33.95  33.77  42.81
3      Andorra        Europe    NaN  26.38    NaN    NaN
4       Angola        Africa    NaN  12.99   9.09  22.69


In [41]:
print(df1.tail())

       Country        Region    CEI    GCI   NCSI    DDL
187  Venezuela        Africa  0.807  27.06  28.57  43.14
188    Vietnam  Asia-Pasific    NaN  94.59  36.36  47.69
189      Yemen  Asia-Pasific    NaN    NaN   7.79    NaN
190     Zambia        Africa  0.745  68.88  55.84  29.66
191   Zimbabwe        Africa  0.724  36.49  15.58  28.97


In [42]:
# Basic DataFrame Operations:
print(df1.shape)
print(df1.columns)
print(df1.describe())
print(df1['Country'])

(192, 6)
Index(['Country', 'Region', 'CEI', 'GCI', 'NCSI', 'DDL'], dtype='object')
              CEI         GCI        NCSI         DDL
count  108.000000  190.000000  167.000000  152.000000
mean     0.471861   52.769526   43.306587   51.707829
std      0.217246   34.884013   26.820907   18.283847
min      0.110000    1.350000    1.300000   11.300000
25%      0.279500   18.257500   19.480000   36.532500
50%      0.483000   53.145000   40.260000   51.790000
75%      0.624250   89.187500   64.940000   65.237500
max      1.000000  100.000000   96.100000   82.930000
0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...     
187      Venezuela
188        Vietnam
189          Yemen
190         Zambia
191       Zimbabwe
Name: Country, Length: 192, dtype: object
